### ISSUE TITLE
Docker-compose auto import projects

### ISSUE THREAD

**Issue by d4rfl0w** [castlemock/docker#13]
Hi,

I have configuration in docker-compose:

```
    mockserver_aggregator:
        image: castlemock/castlemock
        ports:
            - 8080:8080
        volumes:
            - ./_infrastructure/mockserver/.castlemock:/root/.castlemock
```
            
How i can auto import some projects when service start in docker-compose?
